### ISSUE TITLE
Rollup failed to resolve import "codemirror" from "node_modules/svelte-codemirror-editor/CodeMirror.svelte".

### ISSUE THREAD

**Issue by ziyue0230** [obity/hiposter#4]
➜ wails dev
DEB | Using go webview2loader
Wails CLI v2.5.0

Executing: go mod tidy
  • Generating bindings: 
Done.
  • Installing frontend dependencies:
Done.
  • Compiling frontend:
    
    > vite build

    vite v3.2.5 building for production...
    transforming...
    ✓ 352 modules transformed.
    下午5:24:46 [vite-plugin-svelte] dom compile done.
    package     files    time      avg
    frontend      227   3.10s   13.6ms

    [vite]: Rollup failed to resolve import "codemirror" from "node_modules/svelte-codemirror-editor/CodeMirror.svelte".
    This is most likely unintended because it can break your application at runtime.
    If you do want to externalize this module explicitly add it to
    `build.rollupOptions.external`
    error during build:
    Error: [vite]: Rollup failed to resolve import "codemirror" from "node_modules/svelte-codemirror-editor/CodeMirror.svelte".
    This is most likely unintended because it can break your application at runtime.
    If you do want to externalize this module explicitly add it to
    `build.rollupOptions.external`
        
  ERROR   exit status 1

**Comment by wandercn** [comment]
先用命令 wails doctor 检查一下是否缺少什么。
```~ wails doctor
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | MacOS
Version      | 12.0.1
ID           | 21A559
Go Version   | go1.19.5
Platform     | darwin
Architecture | arm64

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2392
Nodejs                    | N/A          | Installed | 18.14.2
npm                       | N/A          | Installed | 9.5.0
```
安装前端插件切换到前端目录
cd frontend
npm i XXX_name -D 

如果是npm下载有些包不成功可以 切换npm源为国内源，把node_modules删除， wails dev重新下载

**Comment by ziyue0230** [comment]
环境应该是没什么问题，
```
# System

OS           | Windows 10 Pro     
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.20.2
Platform     | windows
Architecture | amd64

# Wails

Version | v2.5.0

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 113.0.1774.50
Nodejs     | N/A          | Installed | 14.17.4
npm        | N/A          | Installed | 6.14.14
*upx       | N/A          | Available |
*nsis      | N/A          | Installed | v3.08
```

codemirror 这个模块也是存在的，但仍然引用不了，会报错：

```
 Error: [vite]: Rollup failed to resolve import "codemirror" from "node_modules/svelte-codemirror-editor/CodeMirror.svelte".
    This is most likely unintended because it can break your application at runtime.
    If you do want to externalize this module explicitly add it to
    `build.rollupOptions.external`
```

然而我着实找不到原因。。不知您是否试过在Windows环境下进行调试或者打包，会不会出现同样的问题？

**Comment by wandercn** [comment]
通过在vite.config.js文件的rollupOptions配置中的external数组中添加svelte-codemirror-editor.
```
import {defineConfig} from 'vite'
import {svelte} from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()],
  build: {
    rollupOptions: {
      external: ['svelte-codemirror-editor']
    }
  }

})
```
你这样后再wails dev试试吧。我没在windows环境下试过

**Comment by wandercn** [comment]
```
cd frontend
npm install svelte-codemirror-editor -D
重新下载一次模块试试
```

**Comment by ziyue0230** [comment]
> ```
> cd frontend
> npm install svelte-codemirror-editor -D
> 重新下载一次模块试试
> ```

多谢，已解决！
